### ISSUE TITLE
PinyinTokenFilterFactory 构造 PinyinTokenFilter 输入参数错误

### ISSUE THREAD

**Issue by xautlx** [yida-lxw/IK#1]
`
PinyinTokenFilterFactory 的

    public TokenFilter create(TokenStream input) {
        return new PinyinTokenFilter(input, this.shortPinyin, this.outChinese,
                this.minTermLength);
    }

位置代码应该为：

    public TokenFilter create(TokenStream input) {
        return new PinyinTokenFilter(input, this.shortPinyin, this.pinyinAll, this.outChinese,
                this.minTermLength);
    }
`

**Comment by iamyida** [comment]
Thanks for your correcting,I have made it right like the code you showed.
